CLS
INPUT "entre com valor de L:  "; L
INPUT "entre com valor de P:  "; P

V = L * P
INPUT "entre com valor de j:...."; j
INPUT "entre com valor de c:..."; c
INPUT "entre com valor de v:..."; V

CLS

PRINT "o resultado ...."
PRINT "valor final de V"; V; "este"
PRINT "valor final de j"; j; "teste depois do j"


PRINT "mensagem na tela"

'para enviar para a impressora
'LPRINT "o resultado ...."

'LPRINT "valor final de V"; V; "este"

'LPRINT "valor final de j"; j; "teste depois do j"


